version: "3.6"

services:
  memcached:
    image: docker.io/bitnami/memcached:1
    ports:
      - '11211:11211'
  weatherchallenge:
    build: .
    ports:
      - '8000:80'
    links:
      - 'memcached:memchaced'
    env_file:
      - 'weatherchallenge/.env'
